---
- name: Update the apt cache
  yum: 
    name: "*"
    update_cache: yes
    
- name: Install PHP
  yum: name="{{ item }}" state=installed 
  with_items: "{{ php_packages }}"

- name: Remove apache2
  yum: name={{ apache2_package_name }} state=removed