---
- name: Update the apt cache
  yum: 
    name: "*"
    update_cache: yes
    
- name: Install PHP
  yum: name="{{item}}" state=present 
  with_items:
    - php
    - php-fpm
    - php-mysql
    - php-xml

- name: Remove apache2
  yum: name={{ apache2_package_name }} state=removed