---
- hosts: all
  become: true
  tasks:
    - name: I am able to connect
      ping:
    - name: Install php packages
      yum: name={{item}} state=installed
      with_items:
      - php
      - php-fpm
      - php-mysql
      - php-xml

  # roles:
  #   - demo.php