---
- name: Download docker install script
  command: curl -fsSL get.docker.com -o get-docker.sh
  chdir: /tmp

- name: Install docker
  command: sh get-docker.sh
  chdir: /tmp
  notify:
    - start docker

- name: Add ansible user to docker group
  command: usermod -aG docker {{ ansible_ssh_user }}